name: "modelbase_int8"
platform: "tensorrt"
max_batch_size: 0
input [
  {
    name: "pixel_values"
    data_type: TYPE_INT8
    dims: [ 2,224,224,3 ]
    #reshape { shape: [ 1, 224, 224, 3 ] }
  }
]
output [
  {
    name: "logits"
    data_type: TYPE_INT8
    dims: [ 2,56,56,4 ]
  }
]
