name: "mobilenet"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "input_1"
    data_type: TYPE_FP32
    dims: [ 32,224,224,3 ]
    #reshape { shape: [ 1, 224, 224, 3 ] }
  }
]
output [
  {
    name: "conv2d_9"
    data_type: TYPE_FP32
    dims: [ 32,224,224,4 ]
  }
]
